export const TAB_BAR_DIMENSIONS = {
  PLAY_BAR_HEIGHT: 60,
  PLAY_BAR_WRAPPER_PADDING: 10,
  TAB_BAR_HEIGHT: 50, 
  get TOTAL_HEIGHT() {
    return this.PLAY_BAR_HEIGHT + this.PLAY_BAR_WRAPPER_PADDING + this.TAB_BAR_HEIGHT;
  }
}
